[phases.build]
cmds = [
  "echo -e \"APP_URL=https://nmj-be-production.up.railway.app\\nASSET_URL=https://nmj-be-production.up.railway.app\\nAPP_ENV=development\\nAPP_KEY=base64:...\" > .env",
  "php artisan config:clear",
  "php artisan config:cache",
  "npm install",
  "npm run build",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT" 